---
title: "MAFLD"
output: html_document
date: "2024-06-17"
---

```{r}
library(bibliometrix)
library(tidyverse)
library(fpp3)
```

```{r}
# read combined PubMed dataframe
pubmed_all <- readRDS("../save/rds/pubmed_all")
```

```{r}
colnames(pubmed_all)
```

```{r}
# rename columns
pubmed_all <- pubmed_all %>%
  rename(MESH = DE) %>%
  rename(DE = OT) %>%
  rename(PM = PMID)
```

```{r}
# check duplicates
pubmed_all %>% filter(is.na(PM)) %>% nrow()
pubmed_all %>% group_by(PM) %>% filter(n()>1) %>% ungroup() %>% count(PY)
```

```{r}
# only keep records with distinct PMID

nrow(pubmed_all)
#80238

pubmed_all <- pubmed_all %>% distinct(PM, .keep_all = TRUE)

nrow(pubmed_all)
#74380
```

```{r}
# Removed duplicates
print(80238 - 74380)
```


```{r}
# overwrite DI in a single format by extracting xxx.[DOI] from LID 

pubmed_all <- pubmed_all %>%
  mutate(LID_di = str_extract(LID, "(?<=^|\\s)[^\\s]+(?=\\s\\[DOI\\])"))%>%
  mutate(LID_di = na_if(LID_di, "")) %>%
  mutate(LID_di = str_to_lower(LID_di))
```

```{r}
pubmed_all %>% select(DI, LID, LID_di, SO2) %>% head(n = 30)
```

```{r}
# extract DI from SO2
pubmed_all <- pubmed_all %>%   
  mutate(SO2_di = str_extract(SO2, "(?<=\\s\\DOI\\:\\s).*")) %>%
  mutate(SO2_di = str_remove(SO2_di, "\\.\\sEPUB\\s.*")) %>%
  mutate(SO2_di = str_remove(SO2_di, "\\.\\sECOLLECTION\\s.*")) %>%
  mutate(SO2_di = str_remove(SO2_di, "\\.\\sPRINT\\s.*")) %>%
  mutate(SO2_di = str_remove(SO2_di, "\\.$")) %>%
  mutate(SO2_di = na_if(SO2_di, "")) %>%
  mutate(SO2_di = str_to_lower(SO2_di))
```

```{r}
# overwrite SO2_di as DI
pubmed_all <- pubmed_all %>%
  mutate(DI = str_to_lower(SO2_di))
```

```{r}
# check NA in SO2_di
pubmed_all %>% filter(is.na(SO2_di)) %>% nrow()
```

```{r}
# remove period at the end of TI
pubmed_all <- pubmed_all %>% mutate(TI = str_remove(TI, "\\.$"))
```

```{r}
# format title
gsub_dash <- function(x){
  x <- gsub("\\p{Pd}", "-", x, perl=TRUE)
  x <- gsub("−", "-", x)
  return(x)
}
```

```{r}
# format dash
pubmed_all <- pubmed_all %>% mutate(across(where(is.character), gsub_dash))
```

```{r}
# create publication name
pubmed_all <- pubmed_all %>% mutate(AU_1st = case_when(str_detect(AU, ";") ~ str_extract(AU, "^[^;]+(?=\\;)"),
                            .default = as.character(AU))) %>%
  mutate(AU_sur = str_extract(AU_1st, "^[^\\s]+(?=\\s)")) %>%
  mutate(AU_sur = str_to_title(AU_sur)) %>%
  mutate(AU_gvn = str_extract(AU_1st, "(?<=\\s).+")) %>%
  mutate(PN = paste0(AU_sur, " ", AU_gvn, " (", PY, ")"))
```

```{r}
# check PN
pubmed_all %>% select(PN) %>% View()
```

```{r}
# DI duplicates
pubmed_all %>% filter(!is.na(SO2_di)) %>% group_by(SO2_di) %>% filter(n()>1) %>% select(SO2_di) %>% View()
```

```{r}
# check published year
pubmed_all %>% count(PY)
```

```{r}
# publication record

pubmed_all %>% count(DT) %>% View()
```


```{r}
# check EDAT
pubmed_all %>% filter(is.na(EDAT)) %>% nrow()

pubmed_all %>% select(EDAT) %>% head()
```

```{r}
# format EDAT in date

pubmed_all <- pubmed_all %>% 
  mutate(EDAT = str_replace_all(EDAT, "/", "-")) %>%
  mutate(EDAT = ymd_hm(EDAT)) %>%
  mutate(EDAT = as_date(EDAT)) 
```

```{r}
# check NA in PHST
pubmed_all %>% filter(is.na(PHST)) %>% nrow()
```

```{r}
pubmed_all %>% filter(is.na(PHST)) %>% select(PM, DI, TI, DT, CRDT, starts_with("PHST")) %>% View()
```

```{r}
pubmed_all %>% select(CRDT, PHST)
```

```{r}
pubmed_all %>% select(CRDT) %>% View()
```

```{r}
#if PHST_pubmed is missing, fill with CRDT instead in the format of PHST column

pubmed_all <- pubmed_all %>% 
  mutate(CRDT_phst = paste(CRDT, "[PUBMED]")) %>%
  mutate(PHST_full = case_when(is.na(PHST) ~ CRDT_phst,
                          .default = PHST))

pubmed_all %>% filter(is.na(PHST)) %>% select(PM, DI, CRDT, CRDT_phst, PHST, PHST_full) %>% View()
```

```{r}
pubmed_all %>% filter(is.na(PHST)) %>% select(PM, DI, TI, DT, CRDT, starts_with("PHST"))

```

```{r}
pubmed_all %>%  select(PM, DI, TI, DT, CRDT, starts_with("PHST")) %>% View()
```

```{r}
# separate each component of PHST in long format
pubmed_all_long <- pubmed_all %>% separate_longer_delim(PHST_full, ";")
```

```{r}
pubmed_all_long %>% filter(is.na(PHST)) %>% nrow()
```

```{r}
# change colname PHST to DATE
pubmed_all_long <- pubmed_all_long  %>% rename(DATE = "PHST_full")
```

```{r}
pubmed_all_long  %>%  select(PM, DI, TI, DT, CRDT, starts_with("DATE")) %>% View()
```

```{r}
pubmed_all_long %>% filter(is.na(DATE)) %>% nrow()
```

```{r}
pubmed_all_long  %>% select(PM, DI, TI, DT, CRDT, starts_with("DATE")) %>% View()
```

```{r}
# create date category
pubmed_all_long <- pubmed_all_long %>% 
  mutate(DATE_cat = str_extract(DATE, "(?<=\\[).+(?=\\])")) %>%
  mutate(DATE_cat = str_to_lower(DATE_cat)) %>%
  mutate(DATE_cat = str_replace_all(DATE_cat, "-", "_")) %>%
  mutate(DATE = str_remove(DATE, " \\[.+\\]"))
```

```{r}
pubmed_all_long %>% select(DATE, DATE_cat) %>% View()
```

```{r}
# count PM
pubmed_all_long %>% distinct(PM) %>% nrow()
```

```{r}
pubmed_all_long %>% count(DATE_cat)
# DATE_cat convert success
```

```{r}
pubmed_all_long %>% mutate(DATE_nchar = str_length(DATE)) %>% count(DATE_nchar)
# all 16 characters
```

```{r}
# change DATE_cat into future column name
pubmed_all_long <- pubmed_all_long %>%
  mutate(DATE_cat = paste0("DATE_", DATE_cat))
```

```{r}
pubmed_all_long %>% count(DATE_cat)
# DATE_cat convert success
```

```{r}
pubmed_all_long %>% group_by(PM, DATE_cat) %>% filter(n()>1) %>% nrow()
pubmed_all_long %>% group_by(PM, DATE_cat) %>% filter(n()>1) %>% ungroup() %>% count(DATE_cat)
# only reveived and revised
# remove these rows
```

```{r}
pubmed_all_long %>% group_by(PM, DATE_cat) %>% filter(n()>1) %>% select(starts_with("DATE"), TI, PM, DI) %>% View()
```

```{r}
# some records have duplicated dates for one category
# only keep the earliest dates

nrow(pubmed_all_long)

pubmed_all_long_uni <- pubmed_all_long %>%
  group_by(PM, DATE_cat) %>%
  slice_min(DATE, n = 1) %>%
  ungroup()
  

nrow(pubmed_all_long_uni)
```

```{r}
pubmed_all_long_uni %>% group_by(PM, DATE_cat) %>% filter(n()>1) %>% select(starts_with("DATE"), TI, PM, DI) %>% View()
```

```{r}
# still has duplicates, the same dates not removed by slice_min
nrow(pubmed_all_long_uni)

pubmed_all_long_uni <- pubmed_all_long_uni %>%
  distinct(PM, DATE_cat, .keep_all = TRUE) %>%
  ungroup()

nrow(pubmed_all_long_uni)
```


```{r}
# convert long into wide
# DATE_cat will be the columns
pubmed_all_wide <- pubmed_all_long_uni %>% 
  pivot_wider(names_from = DATE_cat,
              values_from = DATE,
              values_fill = NA)
```

```{r}
pubmed_all_wide %>% View()
```

```{r}
pubmed_all_wide %>% select(starts_with("DATE")) %>% head()
```

```{r}
pubmed_all_wide %>%
  summarise(across(starts_with("DATE"), ~ sum(is.na(.x)) ))
```

```{r}
# format DATE columns in date time

df_pubmed <- pubmed_all_wide %>%
  mutate(across(starts_with("DATE"), ~ str_replace_all(.x, "/", "-"))) %>%
  mutate(across(starts_with("DATE"), ymd_hm)) %>%
  mutate(across(starts_with("DATE"), as_date))

df_pubmed %>% select(starts_with("DATE")) %>% head()
```


```{r}
# format CRDT in date time

df_pubmed <- df_pubmed %>%
  mutate(CRDT = str_replace_all(CRDT, "/", "-")) %>%
  mutate(CRDT = ymd_hm(CRDT)) %>%
  mutate(CRDT = as_date(CRDT))

df_pubmed %>% select(starts_with("DATE")) %>% head()
```


```{r}
df_pubmed %>% filter(is.na(CRDT)) %>% nrow()

df_pubmed %>% filter(is.na(DATE_pubmed)) %>% nrow()
```

```{r}
df_pubmed %>% filter(CRDT != DATE_pubmed) %>% nrow()
```

```{r}
df_pubmed %>% filter(CRDT != DATE_pubmed) %>% select(CRDT, DATE_pubmed,  TI, PM, DI) %>% View()
```

```{r}
df_pubmed %>% filter(CRDT < DATE_pubmed) %>% nrow()

df_pubmed %>% filter(CRDT == DATE_pubmed) %>% nrow()

df_pubmed %>% filter(CRDT > DATE_pubmed) %>% nrow()
```

```{r}
df_pubmed %>% filter(is.na(DATE_pubmed)) %>% nrow()
# zero
```

```{r}
# EDAT and DATE_pubmed is fully equivalent
df_pubmed %>% filter(EDAT < DATE_pubmed) %>% nrow()

df_pubmed %>% filter(EDAT == DATE_pubmed) %>% nrow()

df_pubmed %>% filter(EDAT > DATE_pubmed) %>% nrow()
```

```{r}
# choose DATE_pm (PubMed index date) as the earlier date of CRDT or EDAT

df_pubmed <- df_pubmed %>% 
  mutate(DATE_pm = case_when(CRDT <= EDAT ~ CRDT, 
                             CRDT > EDAT ~ EDAT,
                             .default = NA))
```

```{r}
df_pubmed %>% filter(is.na(DATE_pm)) %>% nrow()
```

```{r}
# check consistency between the year of DATE_pm and published year

df_pubmed %>%
  filter(year(DATE_pm) >= 2010) %>%
  mutate(DATE_pm_yr = year(DATE_pm)) %>%
  mutate(DIFF_py_pm = PY - DATE_pm_yr) %>%
  count(DIFF_py_pm) %>%
  mutate(PCT = n / sum(n) * 100) %>%
  mutate(PCT = round(PCT, digit = 2))

#97.9% 
```

```{r}
df_pubmed %>%
  filter(year(DATE_pm) >= 2010) %>%
  mutate(DATE_pm_yr = year(DATE_pm)) %>%
  mutate(DIFF_py_pm = PY - DATE_pm_yr) %>%
  filter(DIFF_py_pm <= -3) %>%
  select(PM, DI, TI, DIFF_py_pm, DT, PY, DATE_pm, CRDT) %>% View()
```

```{r}
# histogram raw counts
df_pubmed %>%
  filter(year(DATE_pm) >= 2010) %>%
  mutate(DATE_pm_yr = year(DATE_pm)) %>%
  mutate(DIFF_py_pm = PY - DATE_pm_yr) %>%
  count(DIFF_py_pm) %>%
  mutate(DIFF_py_pm = factor(DIFF_py_pm, levels = as.character(seq(-2, 3, 1)))) %>%
  ggplot(aes(DIFF_py_pm, n))+
  geom_col() +
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 50000, 10000),
                     limits = c(0, 50000)) +
  theme_classic()
```


```{r}
# histogram log transformed
df_pubmed %>%
  filter(year(DATE_pm) >= 2010) %>%
  mutate(DATE_pm_yr = year(DATE_pm)) %>%
  mutate(DIFF_py_pm = PY - DATE_pm_yr) %>%
  count(DIFF_py_pm) %>%
  mutate(DIFF_py_pm = factor(DIFF_py_pm, levels = as.character(seq(-2, 3, 1)))) %>%
  ggplot(aes(DIFF_py_pm, n))+
  geom_col() +
  scale_y_continuous(expand = c(0, 0),
                     breaks = c(seq(0, 50000, 10000), 100, 1000, 5000 ),
                     limits = c(0, 50000), trans = "log1p") +
  theme_classic()
```

```{r}
df_pubmed %>%
  filter(year(DATE_pm) >= 2020) %>%
  mutate(DATE_pm_yr = year(DATE_pm)) %>%
  mutate(DIFF_py_pm = PY - DATE_pm_yr) %>%
  count(DIFF_py_pm) %>%
  mutate(PCT = n / sum(n) * 100) %>%
  mutate(PCT = round(PCT, digit = 2))

#97.8 % of papers were indexed the same year or the year before
```

```{r}
df_pubmed %>%
  filter(year(DATE_pm) >= 2020) %>%
  mutate(DATE_pm_yr = year(DATE_pm)) %>%
  mutate(DIFF_py_pm = PY - DATE_pm_yr) %>%
  filter(DIFF_py_pm == 3) %>%
  select(TI, PM, DI, PY, DATE_pm, J9) %>% View()
```


```{r}
df_pubmed %>%
  filter(year(DATE_pm) >= 2020) %>%
  mutate(DATE_pm_yr = year(DATE_pm)) %>%
  mutate(DIFF_py_pm = PY - DATE_pm_yr) %>%
  count(DIFF_py_pm) %>%
  mutate(DIFF_py_pm = factor(DIFF_py_pm, levels = c("-2", "-1", "0", "1", "2", "3"))) %>%
  ggplot(aes(DIFF_py_pm, n))+
  geom_col()+
#  scale_x_continuous(breaks = seq(-3, 4, 1),
#                     limits = c(-3, 4))+
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 30000, 10000),
                     limits = c(0, 30000)) +
  theme_classic()
```

```{r}
df_pubmed %>%
  filter(year(DATE_pm) >= 2020) %>%
  mutate(DATE_pm_yr = year(DATE_pm)) %>%
  mutate(DIFF_py_pm = PY - DATE_pm_yr) %>%
  count(DIFF_py_pm) %>%
  mutate(DIFF_py_pm = factor(DIFF_py_pm, levels = as.character(seq(-2, 3, 1)))) %>%
  ggplot(aes(DIFF_py_pm, n))+
  geom_col()+
  scale_y_continuous(expand = c(0, 0),
                     breaks = c(seq(0, 30000, 10000),10,  100, 1000, 5000 ),
                     limits = c(0, 30000),
                     trans = "log1p") +
  theme_classic()
```

```{r}
df_pubmed %>%
  filter(DATE_pm >= as_date("2023-06-01")) %>%
  mutate(DATE_pm_yr = year(DATE_pm)) %>%
  mutate(DIFF_py_pm = PY - DATE_pm_yr) %>%
  count(DIFF_py_pm) %>%
   mutate(PCT = n / sum(n) * 100) %>%
  mutate(PCT = round(PCT, digit = 2))
```

```{r}
df_pubmed %>%
  filter(DATE_pm >= as_date("2023-06-01")) %>%
  mutate(DATE_pm_yr = year(DATE_pm)) %>%
  mutate(DIFF_py_pm = PY - DATE_pm_yr) %>%
  count(DIFF_py_pm) %>%
  mutate(DIFF_py_pm = factor(DIFF_py_pm, levels = as.character(seq(-2, 1, 1)))) %>%
  ggplot(aes(DIFF_py_pm, n))+
  geom_col()+
  scale_y_continuous(expand = c(0, 0),
                     breaks = c(seq(0, 10000, 1000)),
                     limits = c(0, 10000)) +
  theme_classic()
```

```{r}
df_pubmed %>%
  filter(DATE_pm >= as_date("2023-06-01")) %>%
  mutate(DATE_pm_yr = year(DATE_pm)) %>%
  mutate(DIFF_py_pm = PY - DATE_pm_yr) %>%
  count(DIFF_py_pm) %>%
  mutate(DIFF_py_pm = factor(DIFF_py_pm, levels = as.character(seq(-2, 1, 1)))) %>%
  ggplot(aes(DIFF_py_pm, n))+
  geom_col()+
  scale_y_continuous(expand = c(0, 0),
                     breaks = c(seq(0, 10000, 5000), 10,  100, 500, 1000),
                     limits = c(0, 10000),
                     trans = "log1p") +
  theme_classic()
```

```{r}
nrow(df_pubmed)
```

```{r}
saveRDS(df_pubmed, "../save/rds/df_pubmed")
```

