---
title: "MAFLD"
output: html_document
date: "2024-06-17"
---

```{r}
library(bibliometrix)
library(tidyverse)
library(fpp3)
library(glue)
library(ggtext)
library(patchwork)
```

```{r}
# load pubmed_all before duplicate removal
# only for checking the row numbers
pubmed_all <- readRDS("../save/rds/pubmed_all")
```

```{r}
# load df_pubmed after date
df_pubmed <- readRDS("../save/rds/df_pubmed")
```

```{r}
# check removed duplicates

nrow(pubmed_all)

nrow(df_pubmed)

nrow(pubmed_all) - nrow(df_pubmed)
```


```{r}
# NAFLD terms for detection

nafld <- c("NAFLD", 
           "non-alcoholic fatty liver disease",
           "non alcoholic fatty liver disease",
           "nonalcoholic fatty liver disease")
```

```{r}
# change NAFLD to NASH
# to avoid non-specific match, "NASH" should be used as an independent word

nash_char <-  nafld[nafld != "NAFLD"] %>%
  str_replace("fatty liver disease", "steatohepatitis") %>%
  str_to_upper()

nafld_char <- nafld %>% str_to_upper()

nash_regex <- c("^NASH[[:blank:][:punct:]]",
          "[[:blank:][:punct:]]NASH[[:blank:][:punct:]]",
          "[[:blank:][:punct:]]NASH$")
```

```{r}
# combine NAFLD NASH terms for query

nafld_nash_query <- c(nafld_char, nash_char, nash_regex) %>% paste0(collapse = "|")
nafld_nash_query 
```


```{r}
# MAFLD terms for detection

mafld <- c("MAFLD",
           "metabolic dysfunction associated fatty liver disease",
           "metabolic-dysfunction associated fatty liver disease",
           "metabolic dysfunction-associated fatty liver disease",
           "metabolic-dysfunction-associated fatty liver disease",
           "metabolic \\(dysfunction\\) associated fatty liver disease",
           "metabolic-\\(dysfunction\\) associated fatty liver disease",
           "metabolic \\(dysfunction\\)-associated fatty liver disease",
           "metabolic-\\(dysfunction\\)-associated fatty liver disease",
           "metabolic-associated fatty liver disease",
           "metabolic associated fatty liver disease")
```

```{r}
# create MAFLD query
mafld_query <- paste0(mafld, collapse = "|")
```


```{r}
# MASLD
masld <-  c("MASLD",
            "metabolic dysfunction associated steatotic liver disease",
           "metabolic-dysfunction associated steatotic liver disease",
           "metabolic dysfunction-associated steatotic liver disease",
           "metabolic-dysfunction-associated steatotic liver disease",
           "metabolic \\(dysfunction\\) associated steatotic liver disease",
           "metabolic-\\(dysfunction\\) associated steatotic liver disease",
           "metabolic \\(dysfunction\\)-associated steatotic liver disease",
           "metabolic-\\(dysfunction\\)-associated steatotic liver disease",
           "metabolic-associated steatotic liver disease",
           "metabolic associated steatotic liver disease")
```

```{r}
# do the same procedure for NAFLD/NASH

mash_char <-  masld[masld != "MASLD"] %>%
  str_replace("steatotic liver disease", "steatohepatitis") %>%
  str_to_upper()

masld_char <- masld %>% str_to_upper()

mash_regex <- c("^MASH[[:blank:][:punct:]]",
          "[[:blank:][:punct:]]MASH[[:blank:][:punct:]]",
          "[[:blank:][:punct:]]MASH$")
```

```{r}
# assemble into query
# separate MASLD and MASH

masld_query <- masld_char %>% paste0(collapse = "|")
  
mash_query <- c(mash_char, mash_regex) %>% paste0(collapse = "|")
```

```{r}
nafld_nash_query
mafld_query
masld_query
mash_query
```

```{r}
# detect the presence of each query
# new data frame nmfs (Nafld/Mafld/Fatty/Steaotic)

df_nmfs <- df_pubmed %>%
  mutate(NF = case_when( str_detect(TI, nafld_nash_query) |  str_detect(AB, nafld_nash_query) ~ 1,
                         .default = 0)) %>%
  mutate(MF = case_when( str_detect(TI, mafld_query) |  str_detect(AB, mafld_query) ~ 1,
                         .default = 0)) %>%
  mutate(MASLD = case_when( str_detect(TI, masld_query) |  str_detect(AB, masld_query) ~ 1,
                         .default = 0)) %>%
  mutate(MASH = case_when( str_detect(TI, mash_query) |  str_detect(AB, mash_query) ~ 1,
                         .default = 0)) %>%
  mutate(METALD = case_when( str_detect(TI, "METALD") |  str_detect(AB, "METALD") ~ 1,
                         .default = 0))
```

```{r}
colnames(df_nmfs)
```

```{r}
df_nmfs %>%
  select(NF, MF, MASLD, MASH, METALD) %>%
  summarise(across(c(NF, MF, MASLD, MASH, METALD), ~ sum(.)))
```

```{r}
df_nmfs %>% filter(METALD == 1) %>% select(PM, DI, TI, DE) %>% View()
```

```{r}
# MASLD before proposal -> change to 0
# this is preprint; will be removed anyway so does not matter
df_nmfs %>% filter(MASLD == 1 & DATE_pm < as_date("2023-06-01")) %>% select(TI, DT)
```

```{r}
# MASLD before proposal -> change to 0
df_nmfs <- df_nmfs %>%
  mutate(MASLD = case_when(MASLD == 1 & DATE_pm < as_date("2023-06-01") ~ 0,
                         .default = MASLD))
```

```{r}
# MASLD before proposal -> change to 0
df_nmfs %>% filter(MASH == 1 & DATE_pm < as_date("2023-06-01")) %>% select(TI, PY)
```

```{r}
# MASH before proposal -> change to 0
df_nmfs <- df_nmfs %>%
  mutate(MASH = case_when(MASH == 1 & DATE_pm < as_date("2023-06-01") ~ 0,
                         .default = MASH))
```

```{r}
# MS is MASLD category containing MASLD, MASH and/or METALD
df_nmfs <- df_nmfs %>%
  mutate(MS = case_when( MASLD == 1 | MASH == 1 | METALD == 1 ~ 1,
                         .default = 0))
```


```{r}
# 1 NAFLD alone 
# 2 MAFLD alone
# 3 MASLD alone
# 4 NAFLD and MAFLD
# 5 NAFLD and MASLD
# 6 MAFLD and MASLD
# 7 NAFLD MAFLD MASLD
# 0 otherwise (no term)

df_nmfs <- df_nmfs %>%
  mutate(NMFS_num = case_when( NF == 1 & MF == 0 & MS == 0 ~ "1",
                           NF == 0 & MF == 1 & MS == 0 ~ "2",
                           NF == 0 & MF == 0 & MS == 1 ~ "3",
                           NF == 1 & MF == 1 & MS == 0 ~ "4",
                           NF == 1 & MF == 0 & MS == 1 ~ "5",
                           NF == 0 & MF == 1 & MS == 1 ~ "6",
                           NF == 1 & MF == 1 & MS == 1 ~ "7",
                           NF == 0 & MF == 0 & MS == 0 ~ "0"))
```

```{r}
# 1 NAFLD alone 
# 2 MAFLD alone
# 3 MASLD alone
# 4 NAFLD and MAFLD
# 5 NAFLD and MASLD
# 6 MAFLD and MASLD
# 7 NAFLD MAFLD MASLD
# 0 otherwise (no term)

df_nmfs<- df_nmfs %>%
  mutate(NMFS = case_when( NF == 1 & MF == 0 & MS == 0 ~ "NAFLD",
                           NF == 0 & MF == 1 & MS == 0 ~ "MAFLD",
                           NF == 0 & MF == 0 & MS == 1 ~ "MASLD",
                           NF == 1 & MF == 1 & MS == 0 ~ "NAFLD_MAFLD",
                           NF == 1 & MF == 0 & MS == 1 ~ "NAFLD_MASLD",
                           NF == 0 & MF == 1 & MS == 1 ~ "MAFLD_MASLD",
                           NF == 1 & MF == 1 & MS == 1 ~ "NAFLD_MAFLD_MASLD",
                           NF == 0 & MF == 0 & MS == 0 ~ "0"))
```

```{r}
# remove records with no term

nrow(df_nmfs)

df_nmfs <-  df_nmfs %>%
  filter(NMFS != "0")

nrow(df_nmfs)
```

```{r}
# excluded by lack of disease term
print(74380 - 46006)
```

```{r}
# use index month
df_nmfs <-  df_nmfs %>%
  mutate(DATE_pm = as_date(DATE_pm)) %>%
  mutate(DATE_m = floor_date(DATE_pm, unit = "month"))
```

```{r}
# English

df_nmfs %>% count(LA)
```

```{r}
# filter English, only keep ENG

nrow(df_nmfs)

df_nmfs <-  df_nmfs %>% filter(LA == "ENG")

nrow(df_nmfs)
```

```{r}
# Excluded not English
print(46006 - 44341)
```

```{r}
df_nmfs %>% count(DT) %>% filter(str_detect(DT, "ERRATUM|CORRE"))
```

```{r}
df_nmfs %>% count(DT) %>% filter(str_detect(DT, "RETRACT|WITHDRAW"))
```

```{r}
# remove erratum and retraction

nrow(df_nmfs)

df_nmfs <-  df_nmfs %>% filter(!str_detect(DT, "ERRATUM|RETRACT"))

nrow(df_nmfs)
```

```{r}
# erratum in title
df_nmfs  %>% filter(str_detect(TI, "ERRATUM|CORREG")) %>% select(PM, DI, TI, J9)
```


```{r}
# retraction in title
df_nmfs  %>% filter(str_detect(TI, "RETRACT|WITHDRAW")) %>% select(PM, DI, TI, J9)

# ^WITHDRAW
df_nmfs  %>% filter(str_detect(TI, "^WITHDRAW")) %>% select(PM, DI, TI, J9)
```

```{r}
df_nmfs  %>% filter(str_detect(TI, "^\\[RETRACT|^\\[WITHDRAW")) %>% select(PM, DI, TI, J9)
# zero
```

```{r}
# check DATE_retracted is not NA

df_nmfs %>% filter(is.na(DATE_retracted)) %>% nrow()


df_nmfs %>% filter(!is.na(DATE_retracted)) %>% nrow()


df_nmfs %>% filter(!is.na(DATE_retracted)) %>% select(PM, DI, TI, J9)

# 29329924
# not retracted on original journal website, mistake in indexing?
# do not remove this
```


```{r}
df_nmfs %>% filter(str_detect(TI, "^ERRATUM|^WITHDRAW"))

pm_dt_rm <- df_nmfs %>% filter(str_detect(TI, "^ERRATUM|^WITHDRAW")) %>% pull(PM)
```

```{r}
df_nmfs %>% filter(is.na(TI)) %>% nrow()
```

```{r}
# missing title
df_nmfs %>% filter(is.na(TI)) %>% View()
# electronic book materials -> keep
```


```{r}
# remove 4 based on publication type 
nrow(df_nmfs)

df_nmfs <-  df_nmfs %>% filter(! PM %in% pm_dt_rm) 

nrow(df_nmfs)
```

```{r}
# same title and preprint
df_nmfs %>% group_by(TI) %>% filter(n()>1) %>% filter(str_detect(DT, "PREPRINT")) %>%
  select(PM, DI, TI, J9)
```

```{r}
# title for same title and preprint

ti_dup_pre <- df_nmfs %>% group_by(TI) %>% filter(n()>1) %>% 
  filter(str_detect(DT, "PREPRINT")) %>% pull(TI)
```

```{r}
df_nmfs %>% filter(TI %in% ti_dup_pre) %>%  select(PM, DI, TI, J9) %>% View()

# preprint and accepted papers based on them are both indexed
# can be duplicates -> remove preprint as a whole
```

```{r}
nrow(df_nmfs)

df_nmfs <- df_nmfs %>% filter(! str_detect(DT, "PREPRINT"))

nrow(df_nmfs)
```

```{r}
# removed based on publication type
print(44341 - 44025)
```

```{r}
nrow(df_nmfs)

df_nmfs %>%
  filter(DATE_pm >= as_date("2010-01-01") & DATE_m <= as_date("2024-10-31")) %>%
  nrow()
```

```{r}
nrow(df_nmfs)

df_nmfs %>%
  filter(DATE_m >= as_date("2010-01-01") & DATE_m <= as_date("2024-10-01")) %>%
  nrow()
```

```{r}
nrow(df_nmfs)

df_nmfs %>%
  filter(DATE_m >= as_date("2010-01-01") & DATE_m <= as_date("2024-10-31")) %>%
  nrow()
```


```{r}
# filter 2010 - 2024/10
nrow(df_nmfs)

df_nmfs <- df_nmfs %>%
  filter(DATE_m >= as_date("2010-01-01") & DATE_m <= as_date("2024-10-31"))

nrow(df_nmfs)
```

```{r}
# excluded based on index date
print(44025 -  40791)
```

```{r}
# create column for the year of DATE_pm

df_nmfs <- df_nmfs %>%
  mutate(DATE_pm_yr = year(DATE_pm)) %>%
  mutate(DIFF_py_pm = PY - DATE_pm_yr)
```

```{r}
df_nmfs %>%   count(DIFF_py_pm) %>%
  mutate(PCT = n / sum(n) * 100) %>%
  mutate(PCT = round(PCT, digit = 2))
```

```{r}
# only keep papers indexed before one year ago

nrow(df_nmfs)

df_nmfs <- df_nmfs %>% filter(DIFF_py_pm >= -1)

nrow(df_nmfs)
```

```{r}
# removed by 
print(40864 - 40850)
```

```{r}
# end of selection check removed in total
nrow(df_pubmed)
nrow(df_nmfs)

nrow(df_pubmed) - nrow(df_nmfs)
```

```{r}
# sum up total removed papers
print(5858 + 28374 + 1665 + 316 + 3234 + 14)

# removed records after duplicates

print(28374 + 1665 + 316 + 3234 + 14)
```


```{r}
# save df_nmfs as RDS
saveRDS(df_nmfs, "../save/rds/df_nmfs")
```
