---
title: "MAFLD"
output: html_document
date: "2024-06-17"
---

```{r}
library(bibliometrix)
library(tidyverse)
library(fpp3)
library(glue)
library(ggtext)
library(patchwork)
```

```{r}
# read df_nmfs after all cleaning steps
df_nmfs <- readRDS("../save/rds/df_nmfs")
```

```{r}
# create tsibble for all counts based on NMFS category

tsbl_all <- df_nmfs %>%
  count(DATE_m) %>%
  mutate(DATE_index = yearmonth(DATE_m)) %>%
  mutate(NMFS = "all") %>%
  as_tsibble(index = DATE_index, key = NMFS) %>%
  fill_gaps(n = 0)
```

```{r}
tsbl_all %>% autoplot(n) + theme_classic()
```

```{r}
# plot STL decomposition for overall
p1_a <- tsbl_all  %>%
  model(STL(n ~ trend()+season(), robust = TRUE)) %>%
  components() %>%
  mutate(DATE_m = ym(DATE_index)) %>%
  mutate(DATE_m = as_date(DATE_m)) %>%
  ggplot(aes(DATE_m, trend))+
  geom_line(aes(colour = "Trend"),
            linewidth = 0.6)+
  geom_line(data = tsbl_all,
            aes(DATE_m, n, colour = "Data"),
            linewidth = 0.3, alpha = 1)+
  scale_colour_manual(values=c(Data="#999999",
                               Trend ="black"))+
  scale_x_date(date_labels = "%Y",
               limits = as_date(c("2010-01-01", "2025-01-01")) )+
  scale_y_continuous(breaks = seq(0, 600, 100),
                     limits = c(0, 600))+
  labs(x = "Year", y = "Count",
       title = "NAFLD/MAFLD/MASLD overall",
       tag = "A")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, face="bold"),
        title = element_text(size = 8, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
#        legend.title = element_text(size = 8, colour = "black", face = "bold"),
#        legend.text = element_text(size = 8, colour = "black"), 
        plot.margin = unit(c(0,0,0,0), "mm"))
p1_a
```


```{r}
# containing NAFLD overall
tsbl_nafld_all <- df_nmfs %>%
  filter(NF == 1) %>%
  count(DATE_m) %>%
  mutate(DATE_index = yearmonth(DATE_m)) %>%
  mutate(NMFS = "nafld") %>%
  as_tsibble(index = DATE_index, key = NMFS) %>%
  fill_gaps(n = 0)
```

```{r}
tsbl_nafld_all %>% autoplot(n)+
  theme_classic()
```

```{r}
tsbl_nafld_all %>% filter(n == max(n))

tsbl_nafld_all %>% filter(DATE_m == as_date("2024-10-01"))
# 2023_Mar
```

```{r}
# SLT decomposition
tsbl_nafld_all %>%
  model(STL(n ~ trend(), robust = TRUE)) %>%
  components() %>%
  autoplot()
```

```{r}
tsbl_nafld_all %>%
  model(STL(n ~ trend()+season(), robust = TRUE)) %>%
  components() %>%
  mutate(DATE_m = ym(DATE_index)) %>%
  mutate(DATE_m = as_date(DATE_m))
```


```{r}
# plot STL decomposition for NAFLD all
p1_b <- tsbl_nafld_all %>%
  model(STL(n ~ trend(), robust = TRUE)) %>%
  components() %>%
  mutate(DATE_m = ym(DATE_index)) %>%
  mutate(DATE_m = as_date(DATE_m)) %>%
  ggplot(aes(DATE_m, trend, colour = "Trend")) +
  geom_hline(yintercept = 462,
             colour = "#999999", alpha = 0.5,
             linewidth= 0.3)+
  geom_vline(xintercept = as_date("2023-03-01"),
             colour = "#999999", alpha = 0.5,
             linewidth= 0.3)+
  geom_line(linewidth = 0.6)+
  geom_line(data = tsbl_nafld_all,
            aes(DATE_m, n, colour = "Data"),
            linewidth = 0.3, alpha = 1)+
  scale_colour_manual(values=c(Data="#999999",
                               Trend ="#f781bf"))+

  scale_x_date(breaks = c(seq(as_date("2010-01-01"), as_date("2025-01-01"), by = "5 years"),
                          seq(as_date("2021-01-01"), as_date("2024-01-01"), by = "1 year")),
               date_minor_breaks = "1 year",
               date_labels = "%Y")+
  scale_y_continuous(breaks = c(seq(0, 500, 100), 462),
                     limit = c(0, 500))+
  labs(x = "Year", y = "Count",
       title = "NAFLD overall",
       tag = "B")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, face="bold"),
        title = element_text(size = 8, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
       axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
#        legend.title = element_text(size = 8, colour = "black", face = "bold"),
#        legend.text = element_text(size = 8, colour = "black"), 
        plot.margin = unit(c(0,0,0,0), "mm"))

p1_b
```

```{r}
# containing MAFLD overall
tsbl_mafld_all <- df_nmfs %>%
  filter(MF == 1) %>%
  filter(DATE_m >= as_date("2020-01-01") & DATE_m <= as_date("2024-10-31")) %>%
  count(DATE_m) %>%
  mutate(DATE_index = yearmonth(DATE_m)) %>%
  mutate(NMSF = "mafld") %>%
  as_tsibble(index = DATE_index)
```


```{r}
tsbl_mafld_all
```


```{r}
tsbl_mafld_all %>% autoplot(n)+
  theme_classic()
```

```{r}
# SLT decomposition
tsbl_mafld_all %>%
  model(STL(n ~ trend(), robust = TRUE)) %>%
  components() %>%
  autoplot()
```

```{r}
tsbl_mafld_all %>% filter(n == max(n))
```


```{r}
# plot STL decomposition for MAFLD all
p1_c <- tsbl_mafld_all %>%
  model(STL(n ~ trend()+ season(), robust = TRUE)) %>%
  components() %>%
  mutate(DATE_m = ym(DATE_index)) %>%
  mutate(DATE_m = as_date(DATE_m)) %>%
  ggplot(aes(DATE_m, trend,  colour = "Trend")) +
  geom_line(linewidth = 0.6)+
  geom_line(data = tsbl_mafld_all,
            aes(DATE_m, n, colour = "Data"),
            linewidth = 0.3, alpha = 1)+
  scale_colour_manual(values=c(Data="#999999",
                               Trend ="#ff7f00"))+
  scale_x_date(breaks = c(seq(as_date("2020-01-01"), as_date("2025-01-01"), by = "years")),
               limits = c(as_date("2020-01-01"), as_date("2025-01-01")),
               date_minor_breaks = "1 year",
               date_labels = "%Y")+
  scale_y_continuous(breaks = seq(0, 70, 10),
                     limit = c(0, 70))+
  labs(x = "Year",
       y = "Count",
       title = "MAFLD ovearll",
       tag = "C")+
  theme_classic()+
     theme(plot.tag = element_text(size = 12, face="bold"),
           title = element_text(size = 8, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
#        legend.title = element_text(size = 8, colour = "black", face = "bold"),
#        legend.text = element_text(size = 8, colour = "black"), 
        plot.margin = unit(c(0,0,0,0), "mm"))

p1_c
```


```{r}
# all in one model
mbl_mafld_all <- tsbl_mafld_all %>%
  model(tslm = TSLM(n ~ trend()))
```

```{r}
glance(mbl_mafld_all)
```


```{r}
fit_mafld_all <- mbl_mafld_all %>%
  augment() %>%
  mutate(DATE_m = ym(DATE_index)) %>%
  mutate(DATE_m = as_date(DATE_m))
```


```{r}
fit_mafld_all
```


```{r}
label_mafld_all <- mbl_mafld_all %>% 
  glance() %>% filter(.model == "tslm") %>%
  mutate(label = glue("*p* < 0.001<br>adjusted *R*<sup>2</sup> = {round(adj_r_squared, 2)}"))

label_mafld_all
```


```{r}
label_mafld_all <- mbl_mafld_all %>% 
  glance() %>% filter(.model == "tslm") %>%
  mutate(adj_r_squared = "0.80") %>%
  mutate(label = glue("*p* < 0.001<br>adjusted *R*<sup>2</sup> = {adj_r_squared}"))

label_mafld_all
```


```{r}
p1_d <- fit_mafld_all %>%
  filter(.model == "tslm") %>%
  ggplot(aes(x = DATE_index))+
  geom_line(aes(y = .fitted, colour = "Fitted"),
            linewidth = 0.6) +
  geom_line(aes(y = n, colour = "Data"),
            linewidth = 0.3, alpha = 1)+
  scale_colour_manual(values = c(Data = "#999999",
                                 Fitted = "#ff7f00")) +
  scale_x_yearmonth(breaks = seq(as_date("2020-01-01"), as_date("2025-01-01"), by = "1 year"),
                    limits = c(as_date("2020-01-01"), as_date("2025-01-01")),
                    date_labels = "%Y")+
  scale_y_continuous(breaks = seq(0, 70, 10),
                     limits = c(0, 70))+
  geom_richtext(data = label_mafld_all,
                aes(x = as_date("2020-01-01"), y = 70, label = label),
                size = 2.8,
                hjust =0, vjust = 1,
                fill = NA, label.color = NA)+
  labs(x = "Year",
       y = "Count",
       title = "MAFLD overall",
       tag = "D")+
  theme_classic()+
   theme(plot.tag = element_text(size = 12, face="bold"),
         title = element_text(size = 8, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
#        legend.title = element_text(size = 8, colour = "black", face = "bold"),
#        legend.text = element_text(size = 8, colour = "black"), 
        plot.margin = unit(c(0,0,0,0), "mm"))

p1_d
```

```{r}
# containing MASLD overall
tsbl_masld_all <- df_nmfs %>%
  filter(MS == 1) %>%
  filter(DATE_m >= as_date("2023-06-01") & DATE_m <= as_date("2024-10-31")) %>%
  count(DATE_m) %>%
  mutate(DATE_index = yearmonth(DATE_m)) %>%
  mutate(key = "masld") %>%
  as_tsibble(index = DATE_index)
```

```{r}
tsbl_masld_all
```


```{r}
tsbl_masld_all %>% autoplot(n)+
  theme_classic()
```

```{r}
# SLT decomposition
tsbl_masld_all %>%
  model(STL(n ~ trend() , robust = TRUE)) %>%
  components() %>%
  autoplot()
```

```{r}
tsbl_masld_all %>%
  filter(DATE_m >= as_date("2023-06-01")) %>%
  model(STL(n ~ trend() + season(), robust = TRUE)) %>%
  components() 
```



```{r}
# plot STL decomposition for MAFLD all
tsbl_masld_all %>%
  filter(DATE_m >= as_date("2023-06-01")) %>%
  model(STL(n ~ trend() , robust = TRUE)) %>%
  components() %>%
  mutate(DATE_x = ym(DATE_index)) %>%
  mutate(DATE_x = as_date(DATE_x)) %>%
  ggplot(aes(DATE_x, trend)) +
  geom_line()+
  scale_y_continuous(breaks = seq(0, 300, 100),
                     limit = c(-5, 300))+
  labs(x = "Year", y = "Count")+
  theme_classic()
```

```{r}
mbl_masld_all <- tsbl_masld_all %>%
  model(tslm = TSLM(n ~ trend() ))
```

```{r}
mbl_masld_all %>% glance()
```


```{r}
report(mbl_masld_all)
```

```{r}
fit_masld_all <- mbl_masld_all %>%
  augment() %>%
  mutate(DATE_m = ym(DATE_index)) %>%
  mutate(DATE_m = as_date(DATE_m))
```


```{r}
label_masld_all <- mbl_masld_all %>% glance() %>%
  mutate(label = glue("*p* < 0.001<br>adjusted *R*<sup>2</sup> = {round(adj_r_squared, 2)}"))

label_masld_all
```


```{r}
p1_e <- fit_masld_all %>%
  filter(.model == "tslm") %>%
  ggplot(aes(x = DATE_index))+
  geom_line(aes(y = .fitted, colour = "Fitted"),
            linewidth = 0.6) +
  geom_line(aes(y = n, colour = "Data"),
            linewidth = 0.3, alpha = 1)+
  scale_colour_manual(values = c(Data = "#999999",
                                 Fitted = "#4daf4a")) +
  scale_x_yearmonth(breaks = seq(as_date("2023-07-01"), as_date("2024-07-01"), by = "6 month"),
                  #  limits = c(as_date("2023-06-01"), as_date("2024-08-01")),
                    date_labels = "%Y-%m")+
  scale_y_continuous(breaks = seq(0, 300, 50),
                     limits = c(-20, 300))+
  geom_richtext(data = label_masld_all,
                aes(x = as_date("2023-06-01"), y = 300, label = label),
                size = 2.8,
                hjust =0, vjust = 1,
                fill = NA, label.color = NA)+
  labs(x = "Year",
       y = "Count",
       title = "MASLD overall",
       tag = "E")+
  theme_classic()+
   theme(plot.tag = element_text(size = 12, face="bold"),
         title = element_text(size = 8, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
#        legend.title = element_text(size = 8, colour = "black", face = "bold"),
#        legend.text = element_text(size = 8, colour = "black"), 
        plot.margin = unit(c(0,0,0,0), "mm"))


p1_e
#+
#  guides(colour = guide_legend(title = "Series"))
```

```{r}
p1 <- p1_a + p1_b + p1_c + p1_d + p1_e +
  plot_layout(design = "
  AAA
  BBB
  CDE")
  

p1

ggsave("../figure/Fig1.pdf", p1, width = 175, height = 175, unit = "mm")
```

# end of time series overall
