---
title: "MAFLD"
output: html_document
date: "2024-06-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(bibliometrix)
library(tidyverse)
library(ggtext)
library(glue)
library(patchwork)
library(cowplot)
```


```{r}
# create flow chart for literature search and selection
s1 <- tibble(x= 0:100, y= 0:100)  %>% 
  ggplot(aes(x, y)) +
  scale_x_continuous(minor_breaks = seq(0, 100, 10)) +
  scale_y_continuous(minor_breaks = seq(0, 100, 10)) +
  theme_linedraw()
```

```{r}
# create boxes for literature databases

# left wos #ccebc5
# middle pubmed #fddaec
# right scopus '#fed9a6'

s1 <- s1 +
  geom_rect(xmin = 40, xmax=65, ymin = 94, ymax=100, color='black', fill='#fddaec', size=0.3) +
  annotate('text', x = 41, y = 97,
           label= 'Records identified from PubMed\n[1950 - 2024]\n(n = 80238)',
           size=3.5, hjust = 0, vjust = 0.5)
```

```{r}
# add first exclusion boxes
s1 <- s1 +
  geom_rect(xmin = 50, xmax = 77.5, ymin = 80, ymax = 92, color='black', fill='white', size=0.3) +
    geom_segment(x = 45, xend = 49.5, y = 86, yend = 86, size=0.3, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1.5, "mm"), type= "closed"))
```

```{r}
# text for removed text
s1 <- s1 + annotate('text', x = 51, y = 86,
           label= "Records excluded (n = 39461):\n   Duplicates (n = 5858)\n   No disease term (n = 28374)\n   Not English (n = 1665)\n   Ineligible record type (n = 316)\n   Outside search period (n = 3234)\n   Ineligible index date (n = 14)",
           size = 3.5, hjust = 0, vjust = 0.5)
```

```{r}
s1 <- s1 +
  geom_segment(x = 45, xend = 45, y = 94, yend = 78.5, size=0.3, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1.5, "mm"), type= "closed"))
```


```{r}
s1 <- s1 +
  geom_rect(xmin = 40, xmax = 65, ymin = 60, ymax = 78, color='black', fill='#fddaec', size=0.3) +
  annotate('text', x = 41, y = 69,
           label= 'Eligible records for analysis\n[2010/01 - 2024/10]\n(n = 40777):\n   Category\n      NAFLD (only) (n = 36850)\n      MAFLD (only) (n = 1086)\n      MASLD (only) (n = 1701)\n      NAFLD-MASLD (n = 614)\n      NAFLD-MASLD (n = 426)\n      MAFLD-MASLD (n = 57)\n      All (n = 43)',
           size=3.5, hjust = 0, vjust = 0.5)
```

# pdf

```{r}
s1 <- s1 +
 scale_x_continuous(expand = c(0, 0), limits = c(25, 95)) + 
  scale_y_continuous(expand = c(0, 0), limits = c(59, 101))+
  labs(caption = "Fig. S1. Flow chart for literature selection.")+
  theme_void()+
  theme(plot.caption = element_text(size = 11, hjust = 0, face = "bold"),
        plot.caption.position =  "panel",
        plot.margin = margin(c(25, 25, 120, 25), unit = "mm"))

ggsave("../figure/FigS1.pdf", s1, width = 210, height = 297, units = "mm")
```
